import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import Provider from "./provider";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Принт",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${inter.variable} ${inter.variable} antialiased`}>
        <StackProvider
          app={stackClientApp}
          translationOverrides={{
            "Sign In": "Войти",
            "Sign Up": "Регистрация",
            Email: "Электронная почта",
            Password: "Пароль",
            "Sign in to your account": "Войдите в свой аккаунт",
            "Sign up": "Зарегистрироваться",
            "Already have an account?": "Нет аккаунта?",
            "Create a new account": "Создать новый аккаунт",
            "Repeat Password": "Повторите пароль",
            "Or continue with": "или",
            "Don't have an account?": "Нет аккаунта?",
            "Forgot password?": "Забыли пароль?",
            "Sign in": "Войти",
          }}
        >
          <StackTheme>
            <ConvexClientProvider>
              <Suspense fallback={<div>Загрузка...</div>}>
                <Provider>{children}</Provider>
              </Suspense>
            </ConvexClientProvider>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
